### ISSUE TITLE
Does not seem to work with hugo v0.123.0 and later

### ISSUE THREAD

**Issue by taxilian** [hugomods/images#57] opened 2024-08-10 00:07 UTC
I'm not 100% sure that this is a hugomods/images issue, but since I upgraded past hugo v0.122.0 the hugomods/images plugin no longer works for me, neither the older version or the new current version (which in fairness does say it doesn't work before v0.123.5). I went back and tested on every version up until then using the latest of this plugin but starting with v0.123.0 I get this for all page bundle images:

```
WARN  [github.com/hugomods/images] image not found: SMAF-closeup-connector.jpg
WARN  [github.com/hugomods/images] image not found: SMAF-coil-front-left.jpg?width=360
```

I know the first thing you'd suspect is that I'm not using page bundles correctly, but note that if I disable the plugin these all work just fine -- and they were working on v0.121.1 before I upgraded hugo and they work again if I downgrade back to v0.122.0 even with the current version of the plugin.

My first thought was it might be related to a change in the image name hashing, but that's only affecting the newer versions and this starts before then. It doesn't sound like others are having this issue, but I am completely baffled.

The directory looks like this:

```
    content/blog/my-post-name/
        index.md
        SMAF-closeup-connector.jpg
        SMAF-coil-front-left.jpg
```

the structure is correct as best I can and it contains all images. As I said earlier, disabling the plugin lets hugo find everything. Any suggestions? It seems like it has to be a bug with this plugin since it finds them without, but that also seems like someone else should have encountered it if that's the case

**Comment by razonyang** [comment] 2024-08-10 00:57
I just upgrade Hugo version on GitHub Action for [images docs](https://images.hugomods.com), there is no warning in the [deploy log](https://github.com/hugomods/site/actions/runs/10327586201/job/28593018775).

Would you mind providing an minimal repo to reproduce the issue?

**Comment by taxilian** [comment] 2024-08-10 04:37
I will try to do so probably on Monday, maybe tomorrow if I have time.  Thanks for looking at it

**Comment by razonyang** [comment] 2024-08-10 05:51
No problem, I guess that there is a bug in other place (modules, templates or shortcodes) `include` the partial of this module.

If you're using [HB](https://github.com/hbstack) themes, please try to upgrade all modules (`hugo mod get -u`), and see if this issue is fixed.

**Comment by taxilian** [comment] 2024-08-10 22:36
It turns out the issue was that one of the parent folders didn't have a _index.md file -- the strange thing is that it works fine without the plugin and on older hugo versions (0.122.0 and earlier) but not with the plugin on 0.123.0 and later.

I'm not clear enough on the internals to know if this should be called a bug or not -- it just seems like if it's "correct" enough for hugo then it should be correct enough for the plugin, but if nothing else hopefully this thread will help the next poor sap to hit the issue =]

**Comment by razonyang** [comment] 2024-08-11 04:46
> It turns out the issue was that one of the parent folders didn't have a _index.md file

I didn't see problem on 0.123.0 and later, I create a simple test with multiple versions, as the image shown, there is no `_index.md` in parent folder `content/a`.

![image](https://github.com/user-attachments/assets/3f8838da-e8a9-42c0-a327-5ef921a86c4a)

I just tested 0.124.0 and later, since some modules require 0.124.0 and later.

I'm willing to help if you can provide your source code to reproduce.

**Comment by taxilian** [comment] 2024-08-13 00:02
I've pushed a copy of the site to https://github.com/taxilian/hugo-images-test  -- don't judge me for all the things that aren't done :-P

Here is what is weird -- if I pull that down and run "hugo" it works. I ran it 22 times in a row and it worked .... but on time 23 it failed with 

```
WARN  [github.com/hugomods/images] image not found: Screenshot-2018-01-30-09.12.24-211x300.png
WARN  [github.com/hugomods/images] image not found: BNC-low-angle-front.jpg?width=360
...
```

for lots and lots of images. At present it is working more often than it fails, but if I keep running it enough (or do a hugo serve and change enough files) it will eventually fail.

**Comment by razonyang** [comment] 2024-08-13 02:05
Thanks for providing the reproducible repo, however I'm not able to reproduce this via running `hugo` (`0.132.0`) in 50 times.

https://github.com/user-attachments/assets/cd59e6ee-4961-4112-a6cf-c57d2f04cbe6

I also ran 100 times on hugo `0.131.0`, seems it isn't reproducible for my environment (Windows).

**Comment by taxilian** [comment] 2024-08-13 15:36
Strange; I am on macOS on a case sensitive filesystem; my colleague was also seeing the issue on a similar environment.

```
$ hugo version                                                                                                                                                                                                                                                                                                                                                                                                                        hugo v0.131.0+extended darwin/arm64 BuildDate=2024-08-02T09:03:48Z VendorInfo=brew
```

Since it often works we can work around this, but it's really strange -- and does not actually seem to be related to the presence or absense of that _index.md file as I initially thought. I'm not sure what else to try, but I'll keep poking at it over the next bit and report back if I find anything useful.

**Comment by razonyang** [comment] 2024-08-14 04:30
I tested on Linux (*nix system) with multiple versions via GitHub Actions, still unable to reproduce, full log available on https://github.com/razonyang/hugomods-images-test/actions/runs/10381390111, each job execute `hugo` in 50 times, see the **Build** step for details.

I tried to run on macOS, but that GitHub Action seems not usable on macOS runner, but it should work some as other OSs.

**Comment by razonyang** [comment] 2024-09-03 10:22
I'm closing this for now.

Please let me know if you have any further information by leaving a comment below.

**Closed by razonyang** 2024-09-03 10:22 UTC
